# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c969ed56ec851cd0927a100ca6d95fa8342ae1c5c12732a480f197b0f206b91525e65eab4edb89472bd5aef27879a467b2ac0e3bdd1fe6d7ccd7ce0a7fd9adb

test:
  secret_key_base: 32266a961e12c50ef35d406a26f749553e757a68b41f9770362951ac5752398d96d1f880dcd90041c888be5e36fcd6cb312922dc3b36f4fe4c98ad287a701004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
